### ISSUE TITLE
Isodoc Models latest feedback

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/isodoc-models#18]
* I disagree with renaming elements in different models; certainly the UML model can't cope with that notion. They are either always annexes or always appendixes; they can be named different things in rendering, but the grammars should be transferrable as much as possible. Likewise, references should not be substituted with normRefs, informRefs.

* Do ISO Titles ever include formatting?

* You haven't put DocumentStatus in BibliographicItem yet.

* Presumably Contact Methods include phone, email, postal address, website?

**Comment by ronaldtse** [comment]
* Agree, will fix.
* Doh I did update BibliographicItem/DocumentStatus but forgot to update the PNG. It's there now.
* ISO Titles don't have formatting.
* Yes, we will be using something from a Contact Model.

**Comment by ronaldtse** [comment]
* All fixed now.
