### ISSUE TITLE
Address feedback in IsoDoc wiki: Sections

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc-models#2]
https://github.com/riboseinc/isodoc/wiki/ISODoc:-Text-Sections

Address feedback in IsoDoc wiki: Sections
* annex/subsections take ClauseSections
* annex allows hanging text in the `blocks` attribute
* References contain BibliographicItems
* terms/subsections take TermSections not ClauseSections

**Comment by ronaldtse** [comment]
Fixed in https://github.com/riboseinc/isodoc-models/commit/a234e11e1c44422df2417de7dda4ccd43241284b

**Comment by ronaldtse** [comment]
Question for @opoudjis:

Actually, should a TermSection really contain another TermSection? A ClauseSection can contain a ClauseSection that contains a TermSection, but not a TermSection within a TermSection since we don't want a group of terms colliding with term definitions. A TermSection should be a terminal section?

**Comment by opoudjis** [comment]
TermSections do contain subsections per ISO/IEC DIR 2: 16.4. "Subdivision of the terms and definitions clause is permitted." Example 2 gives: "3. Terms and definitions" follows by "3.2 Surface properties"; "Surface properties" is itself a terms and definitions section.

**Comment by ronaldtse** [comment]
Yes subsections are allowed, but we can equally do a normal section with a subsection as a TermSection?

Unless there is a Term with a definition at the same level as a subsection, it should be sufficient?

**Comment by opoudjis** [comment]
The desired outcome is that a term section contains either a terms collection, or one or more terms sections as subsections. When it has recursive subsections, it is behaving as a normal clause, except that the recursion bottoms out into terms collections rather than paragraphs. Because of that recursive difference, the top level container cannot be called a normal clause section.

**Comment by ronaldtse** [comment]
According to [DIR 2](http://www.iso.org/sites/directives/2016/part2/index.xhtml) Section 16, it seems to imply that a "Term section" should not have a "Term section".

```
Subdivision of the terms and definitions clause is permitted.

Terms and definitions should preferably be listed according to the hierarchy of the concepts (i.e. systematic order). Alphabetical order is the least preferred order.

EXAMPLE 2

3    Terms and definitions
[…]
3.2    Surface properties
3.2.1 
abrasion
loss of material from a surface due to frictional forces
[…]
3.5    Optical properties
[…]
3.5.8
colour retention
degree of permanence of a colour

Note 1 to entry:	Colour retention can be influenced by weathering.

For convenience, the symbols and abbreviated terms may be combined with the terms and definitions in order to bring together terms and their definitions, symbols and abbreviated terms under an appropriate composite title, for example “Terms, definitions, symbols and abbreviated terms”.
```

Notice that the example does not contain a "term" that is in the same clause level as a "term section".

i.e. we can model the top "term section" as a normal "section", and the sections that actually contain "terms" to be "TermSection"'s. We don't need recurrences here -- only the leaf nodes are TermSections.

I think in this case, the document should be considered to have multiple "TermSections", and each of those sections contain terms.

**Comment by ronaldtse** [comment]
i.e.

```
ClauseSection (Terms and definitions)
      |
      v
TermsSection (Types of rice)
      |
      v
TermSection (husked rice)
```
