### ISSUE TITLE
origin is eref, not citation

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/isodoc-models#21]
term/origin is currently a citation. But surely it's a reference to a citation, with a cite-as reference. (Admittedly, in the grammar I use, there is not much use for citations as distinct from erefs.)

**Comment by ronaldtse** [comment]
In UML the distinction between a reference and an attribute is unclear anyway -- are you suggesting we use an arrow relationship to represent the Citation instead of an attribute entry?

**Comment by opoudjis** [comment]
Actually, let's keep the flexibility. It just turns out that I encode both reference to citation and citation as eref. I do need the citeas attribute in origin though; maybe move it to citation from reference to citation?

**Comment by opoudjis** [comment]
The real query here is, whether we will use citation as distinct from eref in a physical model at all. I now think we will not, and that the Logical model should not include both.

**Comment by ronaldtse** [comment]
I think this depends on whether we consider Citation to be part of the document model, or the bibliographic model? I don’t mind getting rid of one of them.

**Comment by opoudjis** [comment]
Huh. I consider it part of the doc model; if it's part of the biblio model, then we need to make sure that only the eref occurs in the doc model, never citation.

**Comment by ronaldtse** [comment]
The problem with moving Citation to the Bib model is that ISO 690 itself is about the "Citation" use of the bib model. Could we keep at least a "BibCitation" (as opposed to a "DocCitation") in the Bib model?

**Comment by opoudjis** [comment]
I propose to leave citation in the bib model, and have eref inherit from citation in the doc model; so there's no need to get rid of citation from the bib model.

**Comment by ronaldtse** [comment]
@opoudjis agree -- could you perform this change in the model then? Thanks!
