### ISSUE TITLE
ISO document with sub-parts apparently now allowed. 

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc-models#28]
ISO/IEC PRF TS 27034-5-1 [Under development]
Information technology -- Security techniques -- Application security -- Part 5-1: Protocols and application security controls data structure -- XML schemas

**Comment by opoudjis** [comment]
That's because it's an IEC document as well, and IEC permits it. ISO-only documents still don't. No need to change anything, we've already allowed for it.

**Comment by ronaldtse** [comment]
That’s what I realized as well, I’d think they would use the lowest common denominator i.e. single parts, but I guess not.
