### ISSUE TITLE
Data model for shortref phrase "ISO 19115-1:2014"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc-models#29]
This came from @andrew2net of https://github.com/riboseinc/isobib

> How do we represent "ISO 19115-1:2014"?

"19115-1" =>  `{IsoDocumentId.projectNumber}-{IsoDocumentId.partNumber}`
":2014" => `:{BibliographicItem.CopyrightAssociation.from.year}`
"ISO " => ???

How do we represent say, "ISO/IEC 27001:2013" or "ISO/IEC/IEEE 29148:2011"?

@opoudjis thoughts?

**Comment by opoudjis** [comment]
ISO is bibdata/contributor[role@type="publisher"]/organization/name = ISO. In our XML:

````
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>ISO</name>
    </organization>
  </contributor>
````

ISO/IEC are represented by multiple instances of bibdata/contributor[@role="publisher"]

**Comment by ronaldtse** [comment]
But "ISO" is an abbreviation, they should be "[en] International Organization for Standardization" (and the other [fr])?

I was thinking of a simple Contact for ISO that contains their contact information too.

**Comment by opoudjis** [comment]
I parse the organisation name to extract the prefix. Do we really need the full name? And bilingual at that? Since I parse it, that's more things that can go wrong. (You could always introduce an abbreviation of an org name, I guess.)

You can put in boilerplate contact if you want. Of course, we don't have a contact model yet.

**Comment by ronaldtse** [comment]
Yes we will need a Contact model later on, but the "Contributor" model is already close to a contact model?

**Comment by opoudjis** [comment]
No addresses though.

Will need decision on whether we allow abbreviation for organisations (as RFC v2 did). I currently insert and recognise only ISO; I can add International Organization for Standardization.

**Comment by ronaldtse** [comment]
We should allow abbreviation (but there can be many abbreviations...), but I wonder if the "ISO" in "ISO XXXX" is not a publisher -- it is a document series?

**Comment by opoudjis** [comment]
You could model it that way, but ISO use the same prefix for everything they publish, so you might as model it that way. In ISO Guide 73, the series is Guide. OTOH in IETF RFC (which is how ISO references them), IETF is the publisher and RFC is the series.

**Comment by ronaldtse** [comment]
OK then let’s support organization abbreviations then!

**Comment by ronaldtse** [comment]
So like this?

"ISO 19115-1:2014"
=>
`{BibItem.publisher.first.abbrev} {IsoDocumentId.projectNumber}-{IsoDocumentId.partNumber} {BibItem.copyright.from.year}`
?

Probably this better?
`{BibItem.publisher.first.abbrev} {IsoDocumentId.projectNumber}-{IsoDocumentId.partNumber} {BibItem.publishedAt.year}`

**Comment by opoudjis** [comment]
Yes, the latter

**Comment by ronaldtse** [comment]
That's egg-cellent 👍

**Comment by opoudjis** [comment]
Done. Am making adjustments to asciidoctor-iso and isodoc

**Comment by ronaldtse** [comment]
Thank you!
