### ISSUE TITLE
Address feedback in IsoDoc wiki: Blocks

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc-models#3]
1. table/identifier, figure/identifier: changed from anchor, need to be consistent (in fact, I'd rather the clause/identifier change to anchor)
1. table/note: note should not be paragraph with footnote, given that tables can be footnoted already
1. table/tbody: tbody obligation is 1..* not 0..*
1. td: I'd be more comfortable with the contents of td being TextElement than paragraph_with_footnote
1. example/list: list in the UML includes callout lists, but callout lists do not belong in example: list needs to be redefined
1. BasicBlock/clause: why is this here? blocks in the logical model receive their clause id from their context, so this does not need to be specified

**Comment by ronaldtse** [comment]
1-3, 6 fixed in https://github.com/riboseinc/isodoc-models/commit/4e7fbdea5e932bc53b529af79235ac46c669e893

4 fixed in https://github.com/riboseinc/isodoc-models/commit/fa417bab3be310c13f303c4aec38082a04139b49

**Comment by opoudjis** [comment]
Five more queries:

. Formula/stemValue, formula/stemType: These can be replaced with formula/InlineFormula (which I will call stem in the grammar`)
. sourcecode, formula, table, example, figure: these do not inherit paragraphs; you should instead add paragraphs to Admonition and Example, and make Paragraph a subclass of BasicBlock.
. sourcecode has a Value attribute of text, for the listing itself
. I would make id an attribute of the superclass BasicBlock; id is an attribute of several of these.
. Actually, both th and td can be either TextTableCell or ParagraphTableCell.

https://github.com/riboseinc/isodoc/wiki/ISODoc:-Text-Blocks

**Comment by ronaldtse** [comment]
@opoudjis I've addressed the issues, and made Paragraph a subclass of BasicBlock. Any further issues?

**Comment by opoudjis** [comment]
I’m still calling FormulaBlock `formula`, it’s InlineForumla that should be renamed `stem` (as you have done).

Otherwise OK.

**Comment by ronaldtse** [comment]
OK renamed `StemBlock` to `FormulaBlock`. Closing this now.
