### ISSUE TITLE
Different sources

### ISSUE THREAD

**Issue by andrew2net** [riboseinc/isodoc-models#30]
`BibliographicItem` can store only one source `+source: Uri[0..1]`. We need to store two more links, `rss` and `obp`.
Suggest changing `+source: Uri[0..1]` to `+sources: SourceUri[0..*]`, and make class `SourceUri` with `uri_type` attribute. Then we can store different types of URLs at the `sources` attribute: `:obp` for OBP-link, `:rss` for RSS and `:src` for a link to a page.

**Comment by opoudjis** [comment]
Done
