### ISSUE TITLE
Should BibItem attribute `source` should be renamed to `links`?

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc-models#31]
Given the issue #30, makes me think if the BibItem attribute `source` should be renamed to `links`?

**Comment by opoudjis** [comment]
... Inclined to agree. Shall I go ahead?

**Comment by ronaldtse** [comment]
Yes please! Thanks @opoudjis !

**Comment by opoudjis** [comment]
Done. None of my code is impacted, since I'm not referring to links at all.
