### ISSUE TITLE
Provide guidance on "Writing an ISO 'Terms and definitions' (and abbreviated terms)" section

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc-models#8]
Document how to achieve this, provide examples as in accordance to ISO/IEC Directives Part 2.

* Terms and defs
* Terms and defs + abbreviated terms (using DL)

**Comment by opoudjis** [comment]
This is in fact a generic task of documenting how to write ISO standards in Asciidoc.

**Comment by opoudjis** [comment]
https://github.com/riboseinc/asciidoctor-iso/wiki/Guidance-for-authoring
