### ISSUE TITLE
Streamline reference elements (internal ref, external ref, bib ref)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/isodoc-models#9]
In UML model, diagram and in code.

**Comment by opoudjis** [comment]
I believe I have done this; at least, I am happy with what I've come up with. @ronaldtse, could you review? Do you want me to feed the streamlining back into the information Model? I would actually prefer to keep the information Model more abstract, and keep the streamlining in the grammar.

**Comment by ronaldtse** [comment]
Yes it’ll be great if you can streamline the model in the same way, so that the model can imply the streamlined grammar.

**Comment by opoudjis** [comment]
I've added footnote and callout. I have not added eref, since it is a reasonable serialisation of ReferenceToCitationElement.
